### PR TITLE
UI Refactoring for Musicmap

### PR DESCRIPTION
**Pull request by justinkchen**
https://github.com/oceanprotocol/ocean-bounties/issues/16

Tracks current device ID when selecting Play and hooks up play/pause/volume functionality to the toolbar.  It also adds in the UI revamps to the track list and player UI

It tracks the player type as a state variable that can be changed via redux to change which player to use. It can then just plug in a new player component as part of the `PlayerContainer` file that checks the `playerType` variable.

### CODE REVIEW

**Comment by Kwinten-C** [comment]
screenshot2
I got it running and provided a screenshot here. UI looks good but some minor changes required:
- tracking bar and surrounding buttons not centered, tracking bar not responsive
- font current track in player too bog
- track item in playlist too high
- hamburger menu in playlist has functions?  

Did you got the player running? Ping me on Gitter if you have more questions or blockers.

**Comment by justinkchen** [comment]
what did you mean by `* track item in playlist too high`?

**Comment by Kwinten-C** [comment]
> 
> 
> what did you mean by `* track item in playlist too high`?

It is the height of each hoirzontal element of each track in the playlist. To make it a bit less high would fit more tracks on the screen, but still within touch-modus safe areas.

**Comment by justinkchen** [comment]
Just pinging here for tracking purposes that this is ready for review with full player functionality already working

**Comment by justinkchen** [comment]
@Kwinten-C or someone else, is this bounty complete?

**Comment by Kwinten-C** [comment]
Thanks. If you think everything is complete, we will test and review it.

**Comment by justinkchen** [comment]
i think it is ready for first review at least, i got all the functionality working i think and fixed up the styling suggestions you made

**Comment by Kwinten-C** [comment]
OK. Thanks for the update! Still not getting player functionality but that might be my problem. I'll look into it. A lot of small remarks though regarding UI, should be easy to fix:

#### BANNER DASHBOARD
- [ ] Back and login button not left aligned (with the container width).

#### PLAYLIST
- [ ] Column titles ("title", "artist", "album", "year",...) not left aligned with underlying columns.
- [ ] Hamburger menu's are too far to the right, need to be right aligned with row lines.
- [ ] TableRow height: change from 49px to 40px.

#### PLAYER

- [ ] Hamburger menu is aligned too far to the right.
- [ ] There should be a max length on volume bar (around 100px).
- [ ] Volume mute button does not work (no effect on volume bar).
- [ ] More spacing between next button and current time.
- [ ] Track metadata is center aligned, should be left aligned, with some spacing.
- [ ] Repeat button is missing.
- [ ] Change player background color to #EDECEF.

**Comment by justinkchen** [comment]
I have made the following changes that you requested and fixed the Repeat button. Also added the ability to play directly from the track list after clicking a new title.

**Comment by justinkchen** [comment]
ezgif com-video-to-gif

**Comment by Kwinten-C** [comment]
I have checked the latest commit with Chrome and Spotify Premium account. Overall it is definitely working but there are some issues. Still some things that need to be fixed:

bounty_revision_ui

1. Bug with playing tracks: after adding a track, the play button refers to the add track functionality
2. Touch areas for next and repeat buttons not circular, keep button size squared, but add spacing next to it
3. Play button does not work as pause: while playing a track it cannot unpause or it plays the track again from the beginning
It also seems that the buttons only work when clicking directly on the icon, not the whole touch area. 
4. The repeat and shuffle buttons are very buggy: they don't always toggle on/off. Sometimes takes multiple clicks.
	Also "on" color is not very clear, use f12034
5. Increase indent of track name: set to 40px
use same right indent for player hamburger
6. Hamburger menus not aligned to the right
7. Track duration is not on the same Y-position as the other track info
8. When rescaling: track duration bar does not decrease, pushing volume bar down
9. Is this font Liberation Sans? Better not to used bold.
10. When rescaling, year and duration columns start to overlap

Also in Firefox, overall functionality is very limited. Many buttons do not work.

**Comment by justinkchen** [comment]
Just turning this into a checklist to work on
- [ ] Bug with playing tracks: after adding a track, the play button refers to the add track functionality
- [x] Touch areas for next and repeat buttons not circular, keep button size squared, but add spacing next to it
- [x] Play button does not work as pause: while playing a track it cannot unpause or it plays the track again from the beginning
- [x] It also seems that the buttons only work when clicking directly on the icon, not the whole touch area.
- [x] The repeat and shuffle buttons are very buggy: they don't always toggle on/off. Sometimes takes multiple clicks.
- [x] Also "on" color is not very clear, use f12034
- [x] Increase indent of track name: set to 40px
- [x] use same right indent for player hamburger
- [x] Hamburger menus not aligned to the right
- [x] Track duration is not on the same Y-position as the other track info
- [ ] When rescaling: track duration bar does not decrease, pushing volume bar down
- [ ] Is this font Liberation Sans? Better not to used bold.
- [ ] When rescaling, year and duration columns start to overlap

**Comment by justinkchen** [comment]
PTAL, i tested and fixed most of those things you mentioned i think and it seems to work in firefox for me as well

**Comment by Kwinten-C** [comment]
Thanks for your input! All checks have passed and all remarks have been implemented. You will receive your Ocean Tokens soon!

**Pull request merged**
